name: ci

on:
  push:
  pull_request:

jobs:
  native:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonbitlang/setup-moonbit@v1
      - run: moon fmt --check
      - run: moon info
      - run: moon check --target native
      - run: moon test --target native
      - run: moon build --target native
      - run: moon run --target native cmd/main -- report examples/minimal/canonical-clean.json
